import React, {useEffect, useState} from 'react';
import styled from 'styled-components';
import LogoImg from '../../../assets/logo/Technology to Customize Your Design _ GraphicSprings - Brave 20-Jun-21 11_44_14 AM.png';
import MaterialTable from 'material-table';

const ReportWrapper = styled.div`
    /* height: 200px; */
    width: 100vw;
    padding: 20px;
    display: flex;
    flex-direction: column;
    /* background-color: #ff8888; */
`;

const LogoWrapper = styled.div`
    height: 110px;
    width: fit-content;
    display: flex;
    align-items: center;
    margin-left: 40px;
    /* background-color: red; */

    img {
        height: 100%;
        /* width: fit-content; */
        flex-grow: 1;
        border-radius: 1rem;
    }

    h1 {
        height: auto;
        margin-left: 5px;
        font-size: 40px;
        color: #006DB6;
    }
`;

const TextContainer = styled.div`
    display: flex;
    flex-direction: column;
    align-items: center;
    /* background-color: #b81212; */

    h2 {
        margin-bottom: 0;
    }
`;

const AllDoctors = styled.div`
    width: 100vw;
    margin-top: 20px;
    background-color: transparent;
`;

export function DoctorReport(props) {
    const [doctorDetails, setDoctorDetails] = useState([]);

    const getDoctorDetails = async () => {
        let response= await fetch("http://localhost:8080/healthgram/test.php",{
            method:"POST",
            header:{"Content-Type": "application/json"},
            body:JSON.stringify({"query":`SELECT * FROM healthgram.tbl_doctor doctor JOIN  healthgram.tbl_userbase userbase On userbase.Username = doctor.Username;`})
        });
        let table = await response.json();
        setDoctorDetails(table);
    }

    useEffect(() => {
        getDoctorDetails()
        setTimeout(() => { 
            window.print()
        }, 1000);
    }, [])

    return <ReportWrapper>
        <LogoWrapper>
            <img src={LogoImg} alt=""/>
            <h1>HealthGram</h1>
        </LogoWrapper>
        <TextContainer>
            <h2>Report Type: Doctor Report</h2>
            <h2>{`Generated by: ${sessionStorage.getItem('Username')}`}</h2>
            <h2>{`Timestamp: ${new Date()}`}</h2>
        </TextContainer>
        <AllDoctors>
            <MaterialTable
                title="Doctors Details"
                data={doctorDetails}
                columns={[
                    { title: "Doc ID", field: "Doc_Id" },
                    { title: "Status", field: "User_Status", lookup: {'verified': '🟢 verified', 'not verified': '🟡 not verified', 'inactive': '⛔ inactive'} },
                    { title: "Specialization ID", field: "Doc_Id" },
                    { title: "Email", field: "Username" },
                    { title: "Name", field: "Doc_Name" },
                    { title: "Phone Number", field: 'Doc_Phone_No', },
                    { title: "DOB", field: "Doc_Dob", },
                    { title: "Registerd on", field: 'Doc_Date_Registered', },
                    { title: "Tokens", field: "Doc_No_Of_Tokens", },
                    { title: "Fee", field: 'Doc_Fee', },
                    { title: "Gender", field: "Doc_Gender", },
                    { title: "Pin Code", field: 'Doc_Pin', },
                ]}
                options={{
                    actionsColumnIndex: 0, addRowPosition: "first",
                    search: false,  
                    paging: false
                }} 
                editable={{                    
                    isEditable: row=> row.Doc_Id==1
                }} 
                style={{
                    height: 'auto',
                    width: '1490px',
                    display: 'flex',
                    boxShadow: 'rgba(136, 165, 191, 0.48) 6px 2px 16px 0px, rgba(255, 255, 255, 0.8) -6px -2px 16px 0px',
                    flexDirection: 'column',
                    borderRadius: '1rem',    
                    marginBottom: '0px'
                    // backgroundColor: 'transparent'
                }}
            />
        </AllDoctors>
        {/* <button onClick={() => console.log(doctorDetails)}>Report</button> */}
    </ReportWrapper>
};