import React, { useEffect, useState } from 'react';
import styled from 'styled-components';
import MaterialTable from 'material-table';
import LogoImg from '../../../assets/logo/Technology to Customize Your Design _ GraphicSprings - Brave 20-Jun-21 11_44_14 AM.png';
import { TablePagination, Grid, Typography, Divider } from '@material-ui/core'

const ReportWrapper = styled.div`
    width: 100vw;
    padding: 20px;
    display: flex;
    flex-direction: column;

`;

const LogoWrapper = styled.div`
    height: 110px;
    width: fit-content;
    display: flex;
    align-items: center;
    margin-left: 40px;
    /* background-color: red; */

    img {
        height: 100%;
        /* width: fit-content; */
        flex-grow: 1;
        border-radius: 1rem;
    }

    h1 {
        height: auto;
        margin-left: 5px;
        font-size: 40px;
        color: #006DB6;
    }
`;

const TextContainer = styled.div`
    display: flex;
    flex-direction: column;
    align-items: center;
    /* background-color: #b81212; */

    h2 {
        margin-bottom: 0;
    }
`;

export function BookingReport(props) {
    const [bookingDetails, setBookingDetails] = useState([])

    const getBookingDetails = async () => {
        let response = await fetch("http://localhost:8080/healthgram/test.php", {
            method:"POST",
            header:{"Content-Type": "application/json"},
            body:JSON.stringify({"query": `SELECT * FROM tbl_booking WHERE Booking_Date BETWEEN '${window.location.href.split('/')[4].substring(0, 10) + ' ' + window.location.href.split('/')[4].substring(13)}' AND '${window.location.href.split('/')[5].substring(0, 10) + ' ' + window.location.href.split('/')[5].substring(13)}';`})
        });
        let table = await response.json();
        setBookingDetails(table)
    }

    useEffect(() => {
        getBookingDetails()
        setTimeout(() => { 
            window.print()
        }, 1000);
    }, [])

    return <ReportWrapper>
        <LogoWrapper>
            <img src={LogoImg} alt=""/>
            <h1>HealthGram</h1>
        </LogoWrapper>
        <TextContainer>
            <h2>Report Type: Patient Report</h2>
            <h2>{`Generated by: ${sessionStorage.getItem('Username')}`}</h2>
            <h2>{`Timestamp: ${new Date()}`}</h2>
        </TextContainer>
        <MaterialTable
                title="Booking Details"
                data={bookingDetails}
                columns={[
                    { title: "Booking Id", field: "Booking_Id", },
                    { title: "Patient Id ", field: "Pat_Id" },
                    { title: "Doctor Id", field: "Doc_Id" },
                    { title: "Prescription Id", field: "Pres_Id" },
                    { title: "Amount", field: "Booking_Amount" },
                    { title: "Time", field: "Booking_Date", },
                    { title: "Status", field: "Booking_Status" },
                ]}
                options={{
                    actionsColumnIndex: 0, addRowPosition: "first",
                    search: false,  
                    paging: false
                }} 
                components={{
                    Pagination: (props) => <>
                        <Grid container style={{ padding:15}}>
                            <Grid sm={6} item><Typography variant="subtitle2">Total Number of Booking :  {props.count}</Typography></Grid>
                        </Grid>
                        <Divider/>
                        <TablePagination {...props} />
                    </>
                }}
                style={{
                    height: 'auto',
                    display: 'flex',
                    marginTop: '35px',
                    boxShadow: 'rgba(136, 165, 191, 0.48) 6px 2px 16px 0px, rgba(255, 255, 255, 0.8) -6px -2px 16px 0px',
                    flexDirection: 'column',
                    borderRadius: '1rem',    
                    padding: '0px 20px'
                    // backgroundColor: 'transparent'
                }}
            />
    </ReportWrapper>
};